![openclassrooms](https://s3.eu-west-1.amazonaws.com/course.oc-static.com/courses/6204541/1+HnqdJ-5ofxiPP9HIxdNdpw.jpeg)

# Transformez vos données en tableaux

Pour cette seconde tâche, nous travaillons toujours sur les mêmes 10 clients, mais nous avons cette fois trois informations à disposition sur chacun d’eux :
- le revenu mensuel
- l'âge du client
- le nombre d’enfants à charge

L’objectif va être de créer un tableau NumPy à partir de ces informations et de répondre aux différentes demandes formulées par notre service prêt en manipulant ce tableau avec les différentes techniques présentées tout au long de ce chapitre.

In [31]:
import numpy as np

L'ensemble des ces informations sont rassemblées dans la liste `tableau` suivante :

In [32]:
hugo = [1800, 21, 0]
richard = [1500, 54, 2]
emilie = [2200, 28, 3]
pierre = [3000, 37, 1]
paul = [2172, 37, 2]
deborah = [5000, 32, 0]
yohann = [1400, 23, 0]
anne = [1200, 25, 1]
thibault = [1100, 19, 0]
emmanuel = [1300, 31, 2]

tableau = [hugo, richard, emilie, pierre, paul, deborah,
           yohann, anne, thibault, emmanuel]

display(tableau)

[[1800, 21, 0],
 [1500, 54, 2],
 [2200, 28, 3],
 [3000, 37, 1],
 [2172, 37, 2],
 [5000, 32, 0],
 [1400, 23, 0],
 [1200, 25, 1],
 [1100, 19, 0],
 [1300, 31, 2]]

A partir de cette liste, créez un array que vous nommerez `data` :

data =

Paul souhaiterait contracter un prêt immobilier :
- affichez les informations qui lui sont relatives. Pour rappel, Paul correspond à la 5ème ligne de nos données
- calculez ses mensualités maximales, en sachant que le taux d'endettement maximum est de 35% (il ne pourra donc pas rembourser par mois plus de 35% de son revenu).

In [37]:
data = np.array(tableau)
print("Les informations relatives à Paul\n", data[4, :])
mensualite_max_paul = round(data[4, 0] * (35 / 100), 2)
print("Les mensualités planchers de Paul s'élèvent à", mensualite_max_paul, "€")

Les informations relatives à Paul
 [2172   37    2]
Les mensualités planchers de Paul s'élèvent à 760.2 €


Un nouveau client vient d'arriver, dont les informations sont les suivantes :

In [34]:
louise = [1900, 31, 1]

Ajoutez ces informations à la suite de votre array `data` :

In [35]:
data = np.vstack((data, louise))
display(data)

array([[1800,   21,    0],
       [1500,   54,    2],
       [2200,   28,    3],
       [3000,   37,    1],
       [2172,   37,    2],
       [5000,   32,    0],
       [1400,   23,    0],
       [1200,   25,    1],
       [1100,   19,    0],
       [1300,   31,    2],
       [1900,   31,    1]])

Stockez enfin l'ensemble des informations de salaire de notre clientèle dans une variable `revenus` :

In [36]:
revenus = data[:, 0]
display(revenus)

array([1800, 1500, 2200, 3000, 2172, 5000, 1400, 1200, 1100, 1300, 1900])

Bien joué !

Comme d'habitude, je vous propose de retrouver la correction ci-contre proposant une solution complète, que ce soit pour vérifier votre travail ou comprendre un point qui aurait été bloquant :
[lien vers la solution](https://colab.research.google.com/github/OpenClassrooms-Student-Center/fr-4452741-decouvrez-les-librairies-python-pour-la-data-science/blob/main/notebooks/P1/P1C4%20-%20Transformez%20vos%20donn%C3%A9es%20en%20tableaux%20-%20correction.ipynb).